import Head from "next/head";
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from "@/components/common/navbar";
import Homepage from "@/components/Homepage";
import Portfolio from "@/components/Portfolio";
import { useState } from "react";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css"; // Import the CSS
import About from "@/components/About";
import Footer from "@/components/common/footer";
import 'aos/dist/aos.css'; // You can also use aos.css here, if you prefer.
import AOS from 'aos';
import { useEffect } from "react";
config.autoAddCss = false; // Tell Font Awesome to skip adding the CSS automatically since it's being imported above



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [isMenuOpen, setMenuOpen] = useState(false);

  useEffect(() => {
    AOS.init({
      duration: 2000, // values from 0 to 3000, with step 50ms
    });
  }, []);

  return (
    <>
      <Head>
        <title>Abdul Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Navbar
          isMenuOpen={isMenuOpen}
          setMenuOpen={setMenuOpen}
        />
        <div className={isMenuOpen ? `${styles.mainContentOpen}` : `${styles.mainContentClosed}`}>
          <Homepage />
          <Portfolio />
          <About />
          <Footer />
        </div>
      </main>
    </>
  )
} 
